### ISSUE TITLE
Firefox javascript:null; error on modal selection

### ISSUE THREAD

**Issue by arintoul** [robertabarton/parent-trail#3]
On Firefox (70.01 64 bit) when the search modal is launched and a selection is made a javascript:null; error is then displayed.
See your demo app https://apex.oracle.com/pls/apex/f?p=69472:2 as an example.
This works fine on Chrome and Edge.
Alan
Ps - the plugin is very useful - thanks for making it available.

**Comment by robertabarton** [comment]
Closed by #4 - thanks to Louis Moreaux !

**Comment by arintoul** [comment]
Thank you for the fix Robert.
